### ISSUE TITLE
MQTTClient do not ping

### ISSUE THREAD

**Issue by vcxk** [adam-fowler/mqtt-nio#100]
the func scheduleTask in class PingreqHandler execute before channel is active;

Maybe you should start it in channelActive in class MQTTMessageHandler;

**Comment by adam-fowler** [comment]
Hmmm I moved it from channelActive because it wasn't triggering.

**Comment by adam-fowler** [comment]
Do you want to try the `main` branch

**Comment by vcxk** [comment]
Not hurry，I  can wait for it.
