### ISSUE TITLE
Xcode preview fails to build with errors

### ISSUE THREAD

**Issue by drmarkpowell** [adam-fowler/mqtt-nio#101]
**Describe the bug**
Adding mqtt-nio dependency to iOS project breaks SwiftUI Previews

**To Reproduce**
1. Create a new iOS app project in Xcode
2. Add mqtt-nio dependency in Swift packages to the app project
3. open ContentView.swift and refresh the Preview. This generates 11 errors :

Undefined symbol: nominal type descriptor for NIOSSL.NIOSSLCertificate
Undefined symbol: nominal type descriptor for NIOSSL.NIOSSLClientTLSProvider
Undefined symbol: NIOSSL.NIOSSLCertificate.toDERBytes() throws -> [Swift.UInt8]
Undefined symbol: static NIOSSL.NIOSSLCertificate.fromPEMFile(Swift.String) throws -> [NIOSSL.NIOSSLCertificate]
Undefined symbol: type metadata accessor for NIOSSL.NIOSSLContext
Undefined symbol: nominal type descriptor for NIOSSL.TLSConfiguration
Undefined symbol: protocol conformance descriptor for NIOSSL.NIOSSLClientTLSProvider<A> : NIOCore.NIOClientTLSProvider in NIOSSL
Undefined symbol: type metadata accessor for NIOSSL.NIOSSLCertificate
Undefined symbol: NIOSSL.NIOSSLContext.__allocating_init(configuration: NIOSSL.TLSConfiguration) throws -> NIOSSL.NIOSSLContext
Undefined symbol: static NIOSSL.TLSConfiguration.makeClientConfiguration() -> NIOSSL.TLSConfiguration
Undefined symbol: NIOSSL.NIOSSLClientTLSProvider.init(context: NIOSSL.NIOSSLContext, serverHostname: Swift.String?, customVerificationCallback: (([NIOSSL.NIOSSLCertificate], NIOCore.EventLoopPromise<NIOSSL.NIOSSLVerificationResult>) -> ())?) throws -> NIOSSL.NIOSSLClientTLSProvider<A>

**Expected behavior**
mqtt-nio builds and runs fine in the iOS simulator and on a real iOS device but breaks previews in Xcode...the preview simulator fails with errors on the build.

**Context (please complete the following information):**
 - Platform [e.g. iOS, macOS, Linux] iOS
 - Swift/Xcode Version: Xcode 13.2.1
 - Version [e.g. 1.2.0] mqtt-nio latest 2.5.2

**Additional context**
I am filing a feedback with Apple as well, as it's equally likely that it's their tool that's broken as the code in mqtt-nio builds and run fine outside of Xcode Preview.

**Comment by drmarkpowell** [comment]
Filed feedback FB9873153 with Apple on Xcode 13.2.1 about these errors in Xcode Preview.

**Comment by drmarkpowell** [comment]
Your intuition is spot-on, my friend!

I forked the repo and removed the conditional platform NOISSL product, and
the Xcode preview worked fine. I will add this data point to the Apple
Feedback and hopefully that will help with a resolution.


On February 1, 2022 at 11:00:31 PM, Adam Fowler ***@***.***)
wrote:

.product(name: "NIOSSL", package: "swift-nio-ssl", condition:
.when(platforms: [.linux, .macOS])),

**Comment by adam-fowler** [comment]
You will need the condition when building a release. Apparently signing applications that include NIOSSL is problematic.

**Comment by obriensp** [comment]
The link errors are coming from some blocks of code in mqtt-nio that are wrapped in `#if canImport(NIOSSL)`. Tweaking the conditional to `#if canImport(NIOSSL) && (os(macOS) || os(Linux))` resolves the errors, which makes me think that when building for SwiftUI Previews NIOSSL is "available" according to the Swift compiler but doesn't get linked in because of the SPM conditional.

@adam-fowler Is that updated `#if` an acceptable fix or is there a better way to express the intent for those parts of the code? Let me know and I can open a PR.

**Comment by drmarkpowell** [comment]
included in the feedback: copied the comment from @obriensp and linked to this issue. Thanks!

**Comment by adam-fowler** [comment]
The fix is now in release 2.5.3
