### ISSUE TITLE
Long payload will cause errors!

### ISSUE THREAD

**Issue by renjun2012** [adam-fowler/mqtt-nio#15]
Thanks author
This is the only library I can find on github that can be used in swift 5.3.
Please fix this bug, thank you very much!

json payload:
{"from":1000000,"to":1234567,"type":1,"content":"I am a beginner in swift and I am studying hard!!测试\n\n test, message","timestamp":1607243024,"nonce":"pAx2EsUuXrVuiIU3GGOGHNbUjzRRdT5b","sign":"ff902e31a6a5f5343d70a3a93ac9f946adf1caccab539c6f3a6"}

client.addPublishListener(named: "My Listener") { result in
            switch result {
            case .success(let publish):
                var buffer = publish.payload
                print(buffer)
                let string = buffer.readString(length: buffer.readableBytes)
                print(string)
            case .failure(let error):
                print("Error while receiving PUBLISH event")
                print(error)
            }
        }
Error while receiving PUBLISH event
MQTTError(status: MQTTNIO.MQTTStatus.MQTTBadResponse)
Error while receiving PUBLISH event
MQTTError(status: MQTTNIO.MQTTStatus.MQTTBadResponse)
Error while receiving PUBLISH event
MQTTError(status: MQTTNIO.MQTTStatus.MQTTBadResponse)

xcode: 12.3 beta, swift: 5.3

**Comment by adam-fowler** [comment]
I have a fix on the `main` branch can you verify this fixes your issue.

**Comment by renjun2012** [comment]
Wow, great, I have passed the test! ! !
Thank you so much for the repair! ! !

**Comment by adam-fowler** [comment]
Great I'll get that into a release today
