### ISSUE TITLE
please add support session present field

### ISSUE THREAD

**Issue by renjun2012** [adam-fowler/mqtt-nio#17]
When the mqtt broker clear session,  need  use the session present field to resubscribe.

thank you support!

**Comment by adam-fowler** [comment]
Yeah it's on my list. Will try to get it done this week

**Comment by renjun2012** [comment]
Great, I will test it immediately after release.
I also tried to add this feature, but unfortunately the level is not enough to contribute code, :-(
Looking forward to your news, thank you!

**Comment by adam-fowler** [comment]
Can you try the code on the main branch. I've added a new `cleanSession` parameter to `MQTT.connect`. Also adding a bunch of code for catching server disconnects

**Comment by renjun2012** [comment]
The test failed, 
the mqtt broker message cannot be received after reconnecting

func MqttConnect() {
        let client = MQTTClient(
            host: "192.168.1.10",
            port: 1883,
            identifier: "test_identifier",
            eventLoopGroupProvider: .createNew,
            configuration: .init(userName:  "my name", password: "my passwd")
        )
        
        try? client.connect(cleanSession: false).wait()
//       Connect for the first time
//        let subscription = MQTTSubscribeInfo(
//            topicFilter: "test_identifier",
//            qos: .exactlyOnce
//        )
//        try? client.subscribe(to: [subscription]).wait()

        
        client.addPublishListener(named: "My Listener") { result in
            switch result {
            case .success(let publish):
//                var buffer = publish.payload
//                let string = buffer.readString(length: buffer.readableBytes)
                  print(string)

            case .failure(let error):
                print("Error while receiving PUBLISH event")
                print(error)
            }
        }
    }

**Comment by adam-fowler** [comment]
@renjun2012 when you added the subscription had you connecting with `cleanSession` set to false? If you connect with `cleanSession` set to true it doesn't save the session.

**Comment by renjun2012** [comment]
yes, cleanSession set false
try? client.connect(cleanSession: false).wait()

Check mqtt broker, the client did not re-subscribe, so no messages can be received.

**Comment by adam-fowler** [comment]
That's weird I have a test with this working https://github.com/adam-fowler/mqtt-nio/blob/c62f6f44311303e490dfb6b4dabfc1af3344851a/Tests/MQTTNIOTests/MQTTNIOTests.swift#L315

**Comment by renjun2012** [comment]
How does the client know that this is a resumed session?
It is obvious that when the client initiates a connection in expecting from a previously established session resume state way, it needs to know whether there is a corresponding session existing in the server, and then it can determine whether the need to re-subscribe after establishing the connection. For this point, from v3.1.1, MQTT protocol has designed the field Session Present for CONNACK packet. This field is used to represent whether the session currently used is new, and the client can judge according to the value of this field.

Original url: https://www.emqx.io/blog/mqtt-session

**Comment by adam-fowler** [comment]
The session is stored on the server. The client doesn't need to know for the subscriptions to be renewed. But I must admit it would be useful for the client to know whether a session already existed. I'll look into that

**Comment by renjun2012** [comment]
> The session is stored on the server. The client doesn't need to know for the subscriptions to be renewed. But I must admit it would be useful for the client to know whether a session already existed. I'll look into that

MQTT v3.1.1does not stipulate when the persistent session should be expired. If only understood from the protocol level, this persistent session should exist forever. However, in the actual scenario, this is not realistic, because it will highly occupy the resource of the server. Therefore, the server usually does not follow the protocol to implementation, but provides a global configuration for limiting the session expiration time.

I think it is necessary to determine whether to re-subscribe according to the field Session Present for CONNACK packet

**Comment by adam-fowler** [comment]
I could get `connect` to return a `EventLoopFuture<Bool>` with the Bool indicating whether a session was present. 
```swift
let sessionPresent = try mqttClient.connect(cleanSession: false).wait()
```
With this I've had to litter my test code with `_ = try mqttClient.connect(...` which is a little annoying

Or allow the user to provide a closure which is supplied whether the session was present.
```
try mqttClient.connect(cleanSession: false) { cleanSession in
    if cleanSession { subscribe to stuff }
}.wait()
```

Thoughts?

**Comment by renjun2012** [comment]
Simple and easy to use, which will make it easier for other developers to use this library
try mqttClient.connect(cleanSession: false, reSubscribe: true).wait()

Finer control:
try mqttClient.connect(cleanSession: false) { sessionPresent in
    if !sessionPresent { subscribe to stuff }
}.wait()

You can choose one according to your open source idea, I can accept both, :-)

**Comment by adam-fowler** [comment]
Having `reSubscribe` implies I have a record of the subscriptions on the client side. This won't necessarily be the case. If a session was stored on the server setting `cleanSession` to false will restore that session along with the subscriptions.

**Comment by adam-fowler** [comment]
Think I go with my original version 
```
let sessionPresent = try mqttClient.connect(cleanSession: false).wait()
```
Users can then do the following if necessary
```swift
mqttClient.connect(cleanSession: false).map { sessionPresent in
    if !sessionPresent {
        subscribe to stuff
    }
}
```

**Comment by renjun2012** [comment]
Yes, autoReSubscribe is not good.


```swift
mqttClient.connect(cleanSession: false).map { sessionPresent in
    if !sessionPresent {
        subscribe to stuff
    }
}
```
This method is better👍

**Comment by adam-fowler** [comment]
That change is in. Maybe you can see if it is returning `sessionPresent == true` on your second connect.

**Comment by renjun2012** [comment]
The sessionPresent function is implemented, and it returns false when the server session state is cleared.

But the strange thing is that I still can't receive messages, I don't know why.
