### ISSUE TITLE
Crashes when subscribing to all topics on mosquitto test server

### ISSUE THREAD

**Issue by theolampert** [adam-fowler/mqtt-nio#18]
**Describe the bug**
Fatal error when subscribing to all topics on mosquito test server.

**To Reproduce**
1. Setup a client as documented
2. Subscribe to `#` on `test.mosquitto.org`
3. After a second or so the library will crash

**Expected behavior**

macOS Big Sur, M1 mini
Swift 5.3, Xcode 12.3

**Additional context**
```shell
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file MQTTNIO/MQTTSerializer.swift, line 160
```

![image](https://user-images.githubusercontent.com/4714866/103011566-721f3680-453a-11eb-8e06-93c04c0adcea.png)

**Comment by adam-fowler** [comment]
I have a fix for this on the main branch

**Comment by theolampert** [comment]
@adam-fowler I can verify that it no longer crashes, thank you.
