### ISSUE TITLE
Failed to Compile; Includes inline assembly

### ISSUE THREAD

**Issue by Ghawken** [adam-fowler/mqtt-nio#19]
**Describe the bug**
Hi Adam

Thanks for this code - it is one of few mqtt libraries that I have found that is able to run independently on WatchOS.  (which I need)
Testing and working well on both iOS and WatchOS 7, stimulators and devices.. Yah!

Unfortunately when i upload to Testflight: I receive this error:

`ITMS-90562: Invalid Bundle - Bitcode failed to compile for your watchOS binary because it includes assembly source code or inline assembly. To resolve this issue, rewrite the corresponding code in a higher-level language such as Objective-C or Swift and redeliver your app.`

At a guess it relates to the CCoreMqtt code?  -- although can't find anything obvious.
Any suggestions or thoughts?  

(Should mention - no other libraries/pods/dependencies, other than those needed/include with mqtt-nio)

Thanks.

**Comment by adam-fowler** [comment]
Could be `swift-nio-ssl`. It does vendor a copy of boringssl. I'd have to have a closer look.

**Comment by Ghawken** [comment]
I think you are right - a quick google finds this

https://github.com/apple/swift-nio-ssl/issues/251

**Comment by adam-fowler** [comment]
I might be able to remove NIOSSL for watchOS builds, event for SSL builds. The iOS, watch OS builds don't use it, they use NIOTransportServices

**Comment by Ghawken** [comment]
Thanks - that would be great.

Meanwhile....
I discovered this fork:
https://github.com/daltonclaybrook/swift-nio-ssl/tree/watch-asm-macro

Set asm and removing all .s files.

I forked this repo; removed package swift-nio-ssl from Package.swift.
Installed (via Add Package Dependency)
Above repo:
https://github.com/daltonclaybrook/swift-nio-ssl/tree/watch-asm-macro
&
then forked mqtt-nio version, minus the standard swift-nio-ssl

So far, runs, and has uploaded without error.  Seems to fix issue currently.

Obviously a bit messy; but hopefully a starting point.

**Comment by adam-fowler** [comment]
Do you want to try #20

**Comment by Ghawken** [comment]
Thanks -  will test asap and update this

**Comment by Ghawken** [comment]
Build error as below:


```
Showing Recent Messages
Undefined symbol: nominal type descriptor for NIOSSL.TLSConfiguration

Undefined symbol: protocol conformance descriptor for NIOSSL.NIOSSLClientTLSProvider<A> : NIO.NIOClientTLSProvider in NIOSSL

Undefined symbol: nominal type descriptor for NIOSSL.NIOSSLClientTLSProvider

Undefined symbol: type metadata for NIOSSL.NIOSSLCertificateSource

Undefined symbol: NIOSSL.defaultCipherSuites.unsafeMutableAddressor : Swift.String

Undefined symbol: type metadata accessor for NIOSSL.NIOSSLContext

Undefined symbol: NIOSSL.NIOSSLContext.__allocating_init(configuration: NIOSSL.TLSConfiguration) throws -> NIOSSL.NIOSSLContext

Undefined symbol: static NIOSSL.TLSConfiguration.forClient(cipherSuites: Swift.String, minimumTLSVersion: NIOSSL.TLSVersion, maximumTLSVersion: NIOSSL.TLSVersion?, certificateVerification: NIOSSL.CertificateVerification, trustRoots: NIOSSL.NIOSSLTrustRoots, certificateChain: [NIOSSL.NIOSSLCertificateSource], privateKey: NIOSSL.NIOSSLPrivateKeySource?, applicationProtocols: [Swift.String], shutdownTimeout: NIO.TimeAmount, keyLogCallback: (NIO.ByteBuffer) -> ()?) -> NIOSSL.TLSConfiguration

Undefined symbol: NIOSSL.NIOSSLClientTLSProvider.init(context: NIOSSL.NIOSSLContext, serverHostname: Swift.String?, customVerificationCallback: ([NIOSSL.NIOSSLCertificate], NIO.EventLoopPromise<NIOSSL.NIOSSLVerificationResult>) -> ()?) throws -> NIOSSL.NIOSSLClientTLSProvider<A>
```

**Comment by adam-fowler** [comment]
#20 merged into main
