### ISSUE TITLE
Ubuntu 18.04 Raspberry Pi 3 - Connection hangs and never succeeds or fails

### ISSUE THREAD

**Issue by ksinghal** [adam-fowler/mqtt-nio#26]
**Describe the bug**
I implemented a simple MQTT Client to connect to Google Cloud IoT. When running on MacOS it works great. However, when using Ubuntu 18.04 on a Raspberry Pi 3, The `try client.connect().wait()` never returns.

**To Reproduce**
1. Implement an MQTT Client
2. Install on Raspberry Pi 3 running Ubuntu 18.04 (bionic)

**Expected behavior**
I would like it to succeed or fail with some specific error

**Context (please complete the following information):**
 - Platform: Linux Ubuntu 18.04
 - Swift/Xcode Version: 5.1.5 and 5.3
 - Version: `main` branch latest

**Comment by adam-fowler** [comment]
Can you get it to work in a Ubuntu 18.04 Docker image on your mac?

**Comment by adam-fowler** [comment]
@ksinghal `MQTTNIO` requires swift 5.3 could that be the reason you are having issues

**Comment by ksinghal** [comment]
@adam-fowler thank you for the quick response! This is an awesome library and I appreciate all the hard work. I will upgrade my raspberry pi to a 64-bit OS so I can run swift 5.3 on it and thus this library. I should probably open a separate issue, but is there a particular dependency or reason for requiring swift 5.3?

**Comment by adam-fowler** [comment]
@ksinghal the 5.3 requirement is so I can add the `where` clause to the NIOSSL dependency. I would try removing that and reverting to 5.1 before you upgrade your raspberry pi

**Comment by ksinghal** [comment]
I had already forked the library to try and run under swift 5.1 and remove the where clause. However, for some reason the EventLoopFuture seems to just hang on swift 5.1. I luckily had the ability to upgrade to a 64-bit OS and install swift 5.3, and was able to get everything working properly. Thank you!
