### ISSUE TITLE
Cannot connect to mqtt broker after upgrading to 1.2.2

### ISSUE THREAD

**Issue by renjunok** [adam-fowler/mqtt-nio#27]
**Describe the bug**
```swift
let client = MQTTClient(
            host: "mqtt.eclipse.org",
            port: 1883,
            identifier: "My Client",
            eventLoopGroupProvider: .createNew
        )
        do {
            try client.connect().wait()
        } catch {
            print(error)
        }
```
connectTimeout(NIO.TimeAmount(nanoseconds: 10000000000))

 - Platform ios 14
 - Swift/Xcode Version: 5.3 / 12.4

I’m not sure if it’s because of my problem, so I need someone’s help to determine this bug
Thank you.

**Comment by adam-fowler** [comment]
Have you tried against v1.2.1 to verify it is the changes in v1.2.2 that are causing the issues.

**Comment by renjunok** [comment]
Not sure what caused the bug
I used xcode spm to add the package, but finally failed. This bug appeared after successfully adding it once.
But I think this may be the reason for the missing package file, so I deleted the package and added it again, but it has been failing now, I am continuing to try.
