### ISSUE TITLE
Use 1.2.2 to report a connection timeout error

### ISSUE THREAD

**Issue by renjunok** [adam-fowler/mqtt-nio#28]
Use 1.2.2 to report a connection timeout error
Sorry, the issue I submitted yesterday was closed, so I had to resubmit a new one

I installed 1.2.2 through spm in a new application and connected to the mqtt server to report:
connectTimeout(NIO.TimeAmount(nanoseconds: 10000000000))

The local mqtt broker is working normally, and other clients can be connected normally
```swift
let client = MQTTClient(
         host: "192.168.1.10",
         port: 1883,
         identifier: "My Client test222",
         eventLoopGroupProvider: .createNew
     )
     do {
         try client.connect(cleanSession: false).wait()
     } catch {
         print(error)
     }
```
I have been confused about this problem for three days. I have tried many solutions but failed. I hope someone can help me, thank you!

Xcode:12.4
swift: 5.3.2

![1619459245150](https://user-images.githubusercontent.com/10955851/116127549-8ea2c980-a6fa-11eb-9ee8-62943bc94665.jpg)

**Comment by adam-fowler** [comment]
Your previous bug was trying to access mqtt.eclipse.org. Is this still not working?

Would you be going through a proxy when accessing your broker?

**Comment by renjunok** [comment]
mqtt.eclipse.org, I can’t connect to the network.
so I use a local server for testing

**Comment by renjunok** [comment]
sorry again, 

everything is normal after restarting the computer, but I don't know the reason!
the problem that has been confused for three days is normal after restarting...

Thank you for your help and support, I am very touched!
😊🤝

**Comment by renjunok** [comment]
sorry again, 

everything is normal after restarting the computer, but I don't know the reason!
the problem that has been confused for three days is normal after restarting...

Thank you for your help and support, I am very touched!
😊🤝
