### ISSUE TITLE
Auto-Reconnect

### ISSUE THREAD

**Issue by ksinghal** [adam-fowler/mqtt-nio#31]
Hello, I connect my devices using MQTT, but rely on a cellular network that drops out occasionally causing a keep-alive failure or other type of disconnection. Currently I am using the following code to auto-reconnect. However, it often does not work. I wanted to see if you had any suggestions @adam-fowler as to the best way to cleanly shutdown and restart the MQTT client.

```
        client.addCloseListener(named: "close") { [unowned self] result in
            DispatchQueue.main.async { [unowned self] in
                switch result {
                case .success:
                    print("MQTT client \(self.clientIdentifier) closed without error")
                    try? self.stopClient()
                    self.client = try? self.createMQTTClient(jwtString: try self.createJWT())
                case .failure(let error):
                    print("MQTT client \(self.clientIdentifier) disconnected with error:")
                    dump(error)
                    try? self.stopClient()
                    self.client = try? self.createMQTTClient(jwtString: try self.createJWT())
                }
            }
        }
```

**Comment by ksinghal** [comment]
Also wanted to add snippets for `closeClient()` and `createMQTTClient(jwtString:)`:

```
    private func createMQTTClient(jwtString: String) throws -> MQTTClient {
        try stopClient()

        return MQTTClient(
            host: Constants.HostURL,
            port: Constants.Port,
            identifier: clientIdentifier,
            eventLoopGroupProvider: .createNew,
            configuration: .init(userName: Constants.UserName,
                                 password: jwtString,
                                 useSSL: true,
                                 tlsConfiguration: .niossl(tlsConfiguration))
        )
    }


    public func stopClient() throws {
        try client?.disconnect().wait()
        try client?.syncShutdownGracefully()
    }
```

**Comment by adam-fowler** [comment]
You shouldn't need to shutdown the client if you lose the connection. You should be able to call
```
client.connect(cleanSession: false)
```
to reconnect. Obviously if you have lost connection because of a lose of network it isn't guaranteed you will reconnect until the network comes back.

**Comment by adam-fowler** [comment]
@ksinghal did this work?

**Comment by adam-fowler** [comment]
Closing as received no response

**Comment by flowbe** [comment]
Hi, I'm trying to achieve an auto-reconnect feature but I'm not sure how to proceed. Right now my code is simply:
```swift
client.addCloseListener(named: "Close listener") { _ in
    DDLogWarn("Connection closed, try to reconnect")
    _ = client.connect(cleanSession: false)
}
```
But I'm not sure if it's the right way to proceed. Perhaps, a built-in auto-reconnect would be nice

**Comment by adam-fowler** [comment]
@flowbe In the [iOS sample](https://github.com/adam-fowler/EmCuTeeTee) I wrote, I have the following. I moved the call to the main thread because I also had some UI changes to make but I guess your code above would work as well. The only thing you'll need to watch out for is you have a small amount of time where you aren't connected and any attempts to send messages over that time will fail.
```swift
self.client.client?.addCloseListener(named: "EmCuTeeTee") { result in
    DispatchQueue.main.async {
        self.connect(cleanSession: false)
    }
}
```

**Comment by flowbe** [comment]
Thanks for your reply. I tried this code but I noticed that it doesn't do what I want because if the reconnect fails then it's over. Here is a sample code for a smarter reconnect method:
```swift
let reconnectDelay: Double = 5
let queue = DispatchQueue(label: "mqttqueue")

client.addCloseListener(named: "Close listener") { _ in
    print("Connection closed")
    queue.async {
        reconnect()
    }
}

func reconnect() {
    guard !client.isActive() else { return }
    print("Reconnecting…")
    do {
        _ = try client.connect(cleanSession: false).wait()
        print("Connection successful")
    } catch {
         print("Error while connecting: \(error)")
         queue.asyncAfter(deadline: .now() + reconnectDelay) {
            self.reconnect()
        }
    }
}
```
