### ISSUE TITLE
Strange error on connect appeared yesterday

### ISSUE THREAD

**Issue by jhoughjr** [adam-fowler/mqtt-nio#40]
Used this lib all day before yesterday and mid day yesterday I started getting this error with MQTTNIO.
Does it with the other fork as well.
That class is private api it seems as there is nothing on google about it.

If u just use URLSession.shared to load a url  I dont see this error.
It has completely broken my app.
Any ideas?

this is from client.connect().wait()

Ive enabled ats exceptions, tried non beta Xcode , everything I can think of.

connecting...
2021-06-22 10:36:33.311011-0500 MQTTTesting[1010:152012] Cannot parse config agent (NSPPrivacyProxyDNSAgent). No data available
2021-06-22 10:36:33.637955-0500 MQTTTesting[1010:152012] Cannot parse config agent (NSPPrivacyProxyDNSAgent). No data available
2021-06-22 10:36:33.641094-0500 MQTTTesting[1010:152012] Cannot parse config agent (NSPPrivacyProxyDNSAgent). No data available
connectTimeout(NIO.TimeAmount(nanoseconds: 10000000000))

**Comment by adam-fowler** [comment]
Is this Jimmy from the Vapor Discord? I saw this somewhere else recently. Just can't remember where. Are you running the iOS 15 beta

**Comment by adam-fowler** [comment]
Found it on the Soto Slack, Someone was struggling to connect to AWS with Soto when using iOS v15 beta. The guy said he couldn't connect with URLSession either.

**Comment by jhoughjr** [comment]
Yep thats me. Till I completely lose my mind. Then idk.
It was literally working all morning yesterday (thats what I get for having fun) then the next run started doing that.
Its such a mystery there is nothing on google about that class.
I was about to start a totally new project to see fi that helps.
Given my luck, its likely an issue only affecting me somehow.
I just dont understand how it worked for hours and hours multiple runs then to never work again when my setup did not change.
If there is anything to test, let me know.

**Comment by jhoughjr** [comment]
I just ran in iPhone 8 simulator and got a normal connection failed message as my Mosquitto isn’t running atm.
That might shed some light on the issue. IM going to continue to poke around and try to isolate it

**Comment by jhoughjr** [comment]
Seems I can connect to test.mosquitto.org <http://test.mosquitto.org/> in the iPhone 8 simulator as well.
(Somehow my Mosquitto is saying im not authored, need to fix that)
Smells like a binary issue like the arm64 bug that swift introduced and didn’t fix for 3 years.
Killed my app cold AND no-one at apple would believe me and just run the sample project I sent.

If it is just an arm64 iOS 15 issue there is likely nothing to be done on your end.

**Comment by jhoughjr** [comment]
The issue doesn't seem to be in mqttnio. Aside from my Mosquitto server saying my app client times out after a couple of minutes, it is working as expected. Im looking to determine the connection state now.

**Comment by adam-fowler** [comment]
Shall I close this then
