### ISSUE TITLE
Build errors with Xcode 13.2

### ISSUE THREAD

**Issue by ffittschen** [adam-fowler/mqtt-nio#93]
**Describe the bug**
Just a heads up, as Xcode 13.2 is still in beta, but we were trying to build an iOS project with mqtt-nio as SPM dependency, which fails when using Xcode 13.2. It throws the following build errors:

> TSTLSConfiguration.swift:11:11: 'tls_protocol_version_t' is only available in iOS 13.0 or newer
> TSTLSConfiguration.swift:45:35: 'tls_protocol_version_t' is only available in iOS 13.0 or newer
> TSTLSConfiguration.swift:48:35: 'tls_protocol_version_t' is only available in iOS 13.0 or newer
> TSTLSConfiguration.swift:65:28: 'tls_protocol_version_t' is only available in iOS 13.0 or newer
> TSTLSConfiguration.swift:66:28: 'tls_protocol_version_t' is only available in iOS 13.0 or newer
> TSTLSConfiguration.swift:65:54: 'TLSv10' is only available in iOS 13.0 or newer

Apple's docs on [tls_protocol_version_t](https://developer.apple.com/documentation/security/tls_protocol_version_t) also list that it is available starting from iOS 13, so my guess is that this happens due to the Package.swift defining iOS 12 as platform: https://github.com/adam-fowler/mqtt-nio/blob/main/Package.swift#L7

**To Reproduce**
1. Integrated mqtt-nio into an iOS project via SPM
2. Build the project using Xcode 13.2

**Expected behavior**
The build should succeed.

**Context (please complete the following information):**
 - Platform: iOS
 - Swift/Xcode Version: Xcode 13.2.0 (13C5066c)
 - Version: 2.1.1

**Comment by adam-fowler** [comment]
That's interesting with Xcode 13.1 there are no issues. I can kinda see why, given the related functions are gated on iOS 13.

**Comment by ffittschen** [comment]
Yeah definitely. I was also surprised when I looked into it and saw that the respective lines were not changes in 12 months, and Xcode 13.0 and 13.1 worked fine

**Comment by adam-fowler** [comment]
PR #94 resolves this but I have also contacted Apple is the hope they can revert this change. Breaking changes between point releases of Xcode shouldn't be acceptable. Hopefully I'll get a response. 

If not I'll merge the PR. It generates a slight breaking change  which is frustrating but then maybe I shouldn't have included this symbol in my public interface.

**Comment by ffittschen** [comment]
I just tested the fix in our project and can verify that the build error is gone. Thanks for the quick help 🙏🏻

**Comment by adam-fowler** [comment]
This is released in v2.5.0
