### ISSUE TITLE
Keep alive messages not sent

### ISSUE THREAD

**Issue by PhilippeWeidmann** [adam-fowler/mqtt-nio#98]
**Describe the bug**
Starting with version 2.5 keepAliveMessages aren't sent anymore. Before version 2.5 we could see the keep alive messages being sent correctly through the web socket.

**To Reproduce**
We use the following configuration to initiate the client:
```
   let configuration = MQTTClient.Configuration(
        keepAliveInterval: .seconds(30),
        connectTimeout: .seconds(20),
        userName: "ips:ips-public",
        password: "password",
        useSSL: true,
        useWebSockets: true,
        webSocketURLPath: "/ws"
    )
   let client = MQTTClient(
        host: "host",
        port: 443,
        identifier: generateClientIdentifier(),
        eventLoopGroupProvider: .createNew,
        configuration: configuration
    )
```

**Expected behavior**
We expect the client to send keep alive messages every 30 seconds as it did with previous versions.

**Context:**
 - Platform iOS
 - Xcode Version: 13
 - Version 2.5

**Comment by adam-fowler** [comment]
There were some internal changes with v2.5. I did verify PINGREQ messages were being sent. Obviously they are not in every situation. I'll have a look. 

Out of interest are you connecting to a v3.1.1 or v5 server.

**Comment by PhilippeWeidmann** [comment]
Hi thank you for your quick response. You assumed correctly, I'm connecting to a 3.1.1 server.

**Comment by adam-fowler** [comment]
Hi @PhilippeWeidmann, can you try the `main` branch to see if it fixed for you

**Comment by PhilippeWeidmann** [comment]
Hi, the latest commit on main seems to have fixed the issue, thank you 😊

**Comment by adam-fowler** [comment]
ok I'll make a new release

**Comment by adam-fowler** [comment]
https://github.com/adam-fowler/mqtt-nio/releases/tag/2.5.1
